export const SERVER_ENDPOINT = "http://localhost:5000"
export const LOGIN_LOCAL_ENDPOINT = "/api/user/login_local"
export const LOGIN_FACEBOOK_ENDPOINT = "/api/user/login_facebook"
export const REGISTER_LOCAL_ENDPOINT = "/api/user/register"
export const CURRENT_USER_ENDPOINT = "/api/user/current"